# Generated by Django 5.1.7 on 2025-03-08 00:34

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Hospital ID')),
                ('hostpital_name', models.CharField(max_length=100)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone number')),
                ('emergency', models.BooleanField(default=False)),
                ('general_beds', models.IntegerField(default=0)),
                ('icu_beds', models.IntegerField(default=0)),
                ('private_beds', models.IntegerField(default=0)),
            ],
        ),
    ]
