# Generated by Django 5.1.7 on 2025-03-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hostpital_name',
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(default=False, max_length=100, verbose_name='Hospital Name'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='emergency',
            field=models.BooleanField(default=False, verbose_name='Emergency Available'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='general_beds',
            field=models.IntegerField(default=0, verbose_name='General Beds'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds',
            field=models.IntegerField(default=0, verbose_name='ICU Beds'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.IntegerField(default=0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='private_beds',
            field=models.IntegerField(default=0, verbose_name='Private Beds'),
        ),
    ]
