# Generated by Django 5.1.7 on 2025-03-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hospital_hostpital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude'),
        ),
    ]
